name: '[💚] Build'

on:
    push:
    pull_request:

jobs:
    build:
        name: '[💚] Build'
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0 # checkout full history

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Set yarn version to latest stable
              run: |
                  corepack enable
                  yarn set version latest

            - name: Get yarn cache directory path
              id: yarn_cache_dir
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

            - name: Restore Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ steps.yarn_cache_dir.outputs.dir }}
                      **/node_modules
                      **/.eslintcache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: |
                  yarn install --immutable

            - name: Run CI Script
              run: |
                  yarn ci

            - name: Show changes
              run: |
                  git --no-pager diff --color-words

            - name: Commit & Push changes
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feat/better-resource-management'
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  message: 'chore: updates by CI'
                  branch: ${{ github.ref_name }}
